# -*- coding: utf-8 -*-
"""TA 10 - Cloning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j264an_eX3dKMXjFby2v2kLoBx6fmloE
"""

import copy

"""## Shallow Cloning Example:

In this shallow cloning example, we create a shallow copy of the ```people``` list using ```copy.copy()```.

When we modify the age of the first person in the cloned list, it affects the original list as well because both lists share references to the same person dictionaries.







"""

# Original list of people
people = [
    {"name": "Alice", "age": 30},
    {"name": "Bob", "age": 25},
    {"name": "Charlie", "age": 35}
]

# Shallow clone of the list
people_clone = copy.copy(people)

# Modify the age of the first person in the cloned list
people_clone[0]["age"] = 40

# Print both lists
print("Original List:")
print(people)

print("\nCloned List:")
print(people_clone)

"""## Deep Cloning Example:

In this deep cloning example, we create a deep copy of the ```people``` list using ```copy.deepcopy()```.

When we modify the age of the first person in the cloned list, it does not affect the original list because the nested dictionaries are also cloned recursively, ensuring that both lists are entirely independent of each other.



"""

# Original list of people
people = [
    {"name": "Alice", "age": 30},
    {"name": "Bob", "age": 25},
    {"name": "Charlie", "age": 35}
]

# Deep clone of the list
people_clone = copy.deepcopy(people)

# Modify the age of the first person in the cloned list
people_clone[0]["age"] = 40

# Print both lists
print("Original List:")
print(people)

print("\nCloned List:")
print(people_clone)

