# -*- coding: utf-8 -*-
"""TA9 - OS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ad3NMfCSoJ0IbbpoA5aZxBIl6s_yCpOs
"""

import os  # Importing the os module

# Get the current working directory
current_directory = os.getcwd()  # Task: File and Directory Operations

# List files and directories in a directory
files_and_directories = os.listdir(current_directory)  # Task: File and Directory Operations

# Create a new directory
os.mkdir("new_directory")  # Task: File and Directory Operations

# Rename a file or directory
os.rename("old_name.txt", "new_name.txt")  # Task: File and Directory Operations

# Delete a file
os.remove("file_to_delete.txt")  # Task: File and Directory Operations

# Check if a file exists
if os.path.exists("file.txt"):  # Task: File and Directory Operations
    print("File exists")
else:
    print("File does not exist")

# Execute a shell command
os.system("ls")  # Task: Process Management

# Get the value of an environment variable
python_path = os.getenv("PYTHONPATH")  # Task: Environment Variables

# Get platform information
platform_name = os.name  # Task: Platform Information
path_separator = os.path.sep  # Task: Platform Information

