# -*- coding: utf-8 -*-
"""TA9 - Files.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NbF6z8xv9CXVhSP4z57X-nxHlrKHFWEs

**Creat new file**
"""

# Creating a new file in write mode
with open("new_file.txt", "w") as file:
    file.write("This is a new file created by Python!\n")

# Creating a new file only if it doesn't exist
with open("new_file.txt", "x") as file:
    file.write("This is a new file created by Python!\n")


# NOTE:
#       This mode is used to create a new file, but if the file already exists, it will raise a FileExistsError.
#       So, if "new_file.txt" does not exist, it will be created, and you'll be able to write to it.

"""**Open exist file**"""

# Opening a file in read mode
file = open("new_file.txt", "r")

# Opening a file in write mode
file = open("new_file.txt", "w")

# Opening a file in append mode
file = open("new_file.txt", "a")


# NOTE:
#       Each call to open() will close the file opened by the previous call and open it again with the new mode.
#       In this case, the file will be open on mode 'a'.

"""For multiple purposes, you can use:
* "r+" for read/write mode
* "a+" for append/read mode.

"""

# Opening a file in read/write mode
file = open("new_file.txt", "r+")

# # Opening a file in append/read mode
# file = open("new_file.txt", "a+")

"""**Reading from an 'open' File**"""

# Reading the entire file
content = file.read()

# Reading a single line
line = file.readline()

# Reading all lines into a list
lines = file.readlines()

print(content)

"""**Wright to exist file**"""

file.write("Hello, World!\n")

"""**Close file**"""

file.close()

"""**'With' block**"""

with open("new_file.txt", "r") as file:
    content = file.read()
    print(content)     # Do something with the content

# File is automatically closed when exiting the 'with' block

"""# **Examples**"""

# Example 1

with open("Example.txt", "w") as file:
    file.write("Hello World!\n")

file = open("Example.txt", "r")
content = file.read()
print(content)

file.close()

# Example 2:

file = open("Example.txt", "a")
file.write("Adding information\n")
# file.close()

file = open("Example.txt", "r")
content = file.read()
print(content)

file.close()

# Example 3

file = open("Example.txt", "w")
file.write("Run Over information\n")
# file.close()

file = open("Example.txt", "r")
content = file.read()
print(content)

file.close()

